baseURL = ""
title = "Owl4Power Team"
languageCode = "en-us"
theme = "hello-friend-ng"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
paginate = 10
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false
themesDir = "themes"

[permalinks]
posts = "/posts/:year/:month/:title/"

[author]
name = "Owl4Power"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Jan 2, 2006"
dateformShort = "Jan 2"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04"
description = "Nice theme for homepages and blogs"
keywords = ""
images = [ "" ]
homeSubtitle = "Hello Friend NG"
disableReadOtherPosts = false
enableThemeToggle = false
enableSharingButtons = true
customCSS = [ ]
customJS = [ ]
justifyContent = false

  [params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true
  topText = [ ]
  bottomText = [
  "",
  ""
]

[params.favicon.color]
mask = "#292a2b"
msapplication = "#292a2b"
theme = "#292a2b"

  [params.logo]
  logoMark = ">"
  logoText = "$ echo owl4power "
  logoHomeLink = "/"

  

[languages.en]
subtitle = "Hello Friend NG Theme"
weight = 1
copyright = '<a href="https://ctf.watadict.com/" target="_blank" rel="noopener">WatadCTF/a>'

[languages.fr]
subtitle = "Hello Friend NG Theme"
weight = 2
copyright = '<a href="https://ctf.watadict.com/" target="_blank" rel="noopener">WatadCTF/a>'

[[menu.main]]
identifier = "about"
name = "About"
url = "about/"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "posts/"
