baseURL = ""
title = "Owl4Power Team"
languageCode = "en-us"
theme = "hello-friend-ng"
PygmentsCodeFences = true
PygmentsStyle = "monokai"
paginate = 10
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
archetypeDir = "archetypes"
contentDir = "content"
dataDir = "data"
layoutDir = "layouts"
publishDir = "public"
buildDrafts = false
buildFuture = false
buildExpired = false
canonifyURLs = false
enableRobotsTXT = false
enableGitInfo = false
enableEmoji = true
enableMissingTranslationPlaceholders = false
disableRSS = false
disableSitemap = false
disable404 = false
disableHugoGeneratorInject = false
themesDir = "themes"

[permalinks]
posts = "/posts/:year/:month/:title/"

[markup.goldmark.renderer]
unsafe= true

[author]
name = "Owl4Power"

[blackfriday]
hrefTargetBlank = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[params]
dateform = "Aug 28, 2021"
dateformShort = "Aug 28"
dateformNum = "2021-08-28"
dateformNumTime = "2021-08-28 10:27"
description = "Nice theme for homepages and blogs"
keywords = ""
images = [ "" ]
homeSubtitle = "Writeups Website"
disableReadOtherPosts = false
enableThemeToggle = false
enableSharingButtons = false
customCSS = [ ]
customJS = [ ]
justifyContent = false

  [params.footer]
  trademark = true
  rss = false
  copyright = false
  author = true
  topText = [ ]
  bottomText = [ ]

[params.favicon.color]
mask = "#292a2b"
msapplication = "#292a2b"
theme = "#292a2b"

  [params.logo]
  logoMark = ">"
  logoText = "$ echo owl4power "
  logoHomeLink = "/"

  



[[menu.main]]
identifier = "about"
name = "About"
url = "about/"

[[menu.main]]
identifier = "Writeups"
name = "Writeups"
url = "posts/"
